# Generated by Django 3.0.6 on 2020-06-01 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Город')),
            ],
            options={
                'verbose_name': 'Город',
                'verbose_name_plural': 'Города',
            },
        ),
        migrations.CreateModel(
            name='Weather',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_name', models.CharField(max_length=50, verbose_name='Название города')),
                ('temperature', models.PositiveSmallIntegerField(default=0, verbose_name='Температура')),
                ('wind_speed', models.PositiveSmallIntegerField(default=0, verbose_name='Скорость ветра')),
                ('weather_condition', models.CharField(max_length=50, verbose_name='Погода')),
                ('weather_icon_id', models.CharField(max_length=5, verbose_name='Иконка погоды')),
                ('time', models.DateTimeField(auto_now=True, verbose_name='Вермя последнего обновления')),
            ],
            options={
                'verbose_name': 'Информация о погоде',
                'verbose_name_plural': 'Информация о погоде',
            },
        ),
    ]
