# Generated by Django 3.0.6 on 2020-06-01 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weather',
            name='temperature',
            field=models.FloatField(default=0, verbose_name='Температура'),
        ),
        migrations.AlterField(
            model_name='weather',
            name='wind_speed',
            field=models.FloatField(default=0, verbose_name='Скорость ветра'),
        ),
    ]
