# Generated by Django 3.0.6 on 2020-05-31 11:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=35, verbose_name='Имя абонента')),
                ('surname', models.CharField(max_length=35, verbose_name='Фамилия абонента')),
                ('patronymic_name', models.CharField(max_length=35, verbose_name='Отчество абонента')),
                ('address', models.CharField(max_length=70, verbose_name='Адрес')),
                ('city', models.CharField(max_length=50, verbose_name='Город')),
            ],
            options={
                'verbose_name': 'Абонент',
                'verbose_name_plural': 'Абоненты',
            },
        ),
        migrations.CreateModel(
            name='PhoneNumber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=35, verbose_name='Номер телефона')),
                ('type_of_number', models.CharField(choices=[('МОБИЛЬНЫЙ', 'Мобильный'), ('ДОМАШНИЙ', 'Домашний')], max_length=35, verbose_name='Тип телефона')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phones', to='book.Person')),
            ],
            options={
                'verbose_name': 'Номер',
                'verbose_name_plural': 'Номера',
            },
        ),
    ]
