# Generated by Django 3.0.6 on 2020-05-31 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phonenumber',
            name='type_of_number',
            field=models.CharField(choices=[('Мобильный', 'МОБИЛЬНЫЙ'), ('Домашний', 'ДОМАШНИЙ')], max_length=35, verbose_name='Тип телефона'),
        ),
    ]
